// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1djKXa6vP3IV3uK1BB7H2-UjUdE5OuV0',
    appId: '1:512110244660:web:14a6ffbc9526a3d5c1ab61',
    messagingSenderId: '512110244660',
    projectId: 'to-do-app-da7b2',
    authDomain: 'to-do-app-da7b2.firebaseapp.com',
    storageBucket: 'to-do-app-da7b2.firebasestorage.app',
    measurementId: 'G-Z99EF9V8XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5V_ueflTuFqCf_Rtka3TkjfhbbtX_yU',
    appId: '1:512110244660:android:434fd64d9c9893fac1ab61',
    messagingSenderId: '512110244660',
    projectId: 'to-do-app-da7b2',
    storageBucket: 'to-do-app-da7b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1vzoiTFMFxqjcJeMifHqJ9geBSuONd0',
    appId: '1:512110244660:ios:e2364189929e5d12c1ab61',
    messagingSenderId: '512110244660',
    projectId: 'to-do-app-da7b2',
    storageBucket: 'to-do-app-da7b2.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1vzoiTFMFxqjcJeMifHqJ9geBSuONd0',
    appId: '1:512110244660:ios:e2364189929e5d12c1ab61',
    messagingSenderId: '512110244660',
    projectId: 'to-do-app-da7b2',
    storageBucket: 'to-do-app-da7b2.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1djKXa6vP3IV3uK1BB7H2-UjUdE5OuV0',
    appId: '1:512110244660:web:ca3c0853d217c9c8c1ab61',
    messagingSenderId: '512110244660',
    projectId: 'to-do-app-da7b2',
    authDomain: 'to-do-app-da7b2.firebaseapp.com',
    storageBucket: 'to-do-app-da7b2.firebasestorage.app',
    measurementId: 'G-F0SK9DB1KX',
  );
}
